### ISSUE TITLE
Request : Option to auto populate Comment of final check-in

### ISSUE THREAD

**Issue by IanScull** [DieterVantilt/TeamMerge#3]
For the final check-in of the merge change set would it be possible to have an option setting that would auto-populate the check-in Comment with either a fixed comment or a list of the work-item IDs that were merged (e.g. "Merged : 100,103,1004,105,110").

As one of our check-in polices is to enforce comments on check-ins this would help improve the consolidated merge process even further.

**Comment by dieter-vantilt** [comment]
I like this idea and will add this feature in the next release.

**Comment by dieter-vantilt** [comment]
I made the modifications and created a new release. Can you let me know if this is what you wanted so I can close this issue?

**Comment by IanScull** [comment]
Works Perfectly many thanks



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
