### ISSUE TITLE
Can't be installed on Visual Studio 2019

### ISSUE THREAD

**Issue by LucasLibis** [DieterVantilt/TeamMerge#4]
Hello,

I can't install this extension on Visual Studio 2019 (version 16.0.1). Do you plan to support VS 2019 or is there something I can do to make it work?

Best regards,

**Comment by DieterVantilt** [comment]
Hey Lucas

I'm almost done with the modifications for this extension. On the dev branch you can find a possible release candidate for the extension but I'm currently testing it. I'm planning on releasing it to the Visual Studio Marketplace this evening.

Regards

**Comment by LucasLibis** [comment]
Hi,

Great news! I'll wait for the release

thanks

**Comment by DieterVantilt** [comment]
The extension has been released! Let me know if it works on your Visual Studio 2019 then we close this issue. If you run into any problem, let me know.

Regards

**Comment by LucasLibis** [comment]
Hello,

It works great on my Visual Studio.

Thank you very much

**Comment by DieterVantilt** [comment]
Np!
