### ISSUE TITLE
 Request : Option to auto populate Comment of final check-in

### ISSUE THREAD

**Issue by Two-Fishes** [DieterVantilt/TeamMerge#5]
I also need this option, but I couldn't find it in the latest Release.

But I still need a little more:
1) I'd like to append the Changeset ids to the comment if not all changesets are selected. 
Example: Merge Branch1 -> Branch 2 (CS1111,1234)
But if all changsets are selected, I'd like to append "Latest Version" instead of the Changset ids
Example: Merge Branch1 -> Branch 2 (Latest Version)
2) Exclude all WorkItems at once

I already made this changes in a local copy, because this are only small changes, but for every new release I have to make the changes again.

**Comment by dieter-vantilt** [comment]
I will look into this

**Comment by Two-Fishes** [comment]
Great. Thanks.

**Comment by dieter-vantilt** [comment]
There is a new version available 2.1.0. Can you look if these changes are what you wanted?

**Comment by Two-Fishes** [comment]
Thanks. Yes, that's almost what I wanted. But I wanted to add the ChangesetIds to the comment instead of the WorkItemIds.

**Comment by dieter-vantilt** [comment]
Ah I overlooked the question. If I find some time this week I will add this last thing!

**Comment by Two-Fishes** [comment]
No problem. Thanks for your fast responses and implementation.

**Comment by Two-Fishes** [comment]
Sorry for asking, but did you forget about that issue?

**Comment by DieterVantilt** [comment]
Ah sorry. I did forget about it... My bad. I should have some time this week to complete it!

**Comment by dieter-vantilt** [comment]
Version 2.2.0 has just been released and should contain your last requested change. Can you take a look and tell me if this is what you wanted? 
If there is still something I overlooked let me know! 
If everything is alright then we can close this issue.

**Comment by Two-Fishes** [comment]
I've testet the new version and everthing is ok. Thank you very much for your reply and work.
